# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# YAML anchor for services that depend on Kafka
# This template can be reused with 
# <<: *kafka-service 
# to avoid duplication
x-kafka-service: &kafka-service
  depends_on:
    kafka:
      condition: service_healthy
  environment:
    - KAFKA_ADDR=${KAFKA_HOST}:${KAFKA_PORT}

services:
  accounting:
    <<: *kafka-service

  checkout:
    <<: *kafka-service
  
  fraud-detection:
    <<: *kafka-service
      
  frontend-proxy:
    depends_on:
      load-generator:
        condition: service_started
