apiVersion: skaffold/v3
kind: Config
metadata:
  name: opentelemetry-demo
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false # Defaults to false for local clusters, true for remote
    tryImportMissing: true # Don't rebuild if the image already exists locally
    useBuildkit: true
  artifacts:
  - image: otel-demo/accounting
    context: .
    docker:
      dockerfile: src/accounting/Dockerfile
  - image: otel-demo/ad
    context: .
    docker:
      dockerfile: src/ad/Dockerfile
  - image: otel-demo/cart
    context: .
    docker:
      dockerfile: src/cart/src/Dockerfile
  - image: otel-demo/checkout
    context: .
    docker:
      dockerfile: src/checkout/Dockerfile
  - image: otel-demo/currency
    context: .
    docker:
      dockerfile: src/currency/Dockerfile
  - image: otel-demo/email
    context: .
    docker:
      dockerfile: src/email/Dockerfile
  - image: otel-demo/flagd-ui
    context: .
    docker:
      dockerfile: src/flagd-ui/Dockerfile
  - image: otel-demo/fraud-detection
    context: .
    docker:
      dockerfile: src/fraud-detection/Dockerfile
  - image: otel-demo/frontend
    context: .
    docker:
      dockerfile: src/frontend/Dockerfile
  - image: otel-demo/frontend-proxy
    context: .
    docker:
      dockerfile: src/frontend-proxy/Dockerfile
  - image: otel-demo/image-provider
    context: .
    docker:
      dockerfile: src/image-provider/Dockerfile
  - image: otel-demo/kafka
    context: .
    docker:
      dockerfile: src/kafka/Dockerfile
  - image: otel-demo/load-generator
    context: .
    docker:
      dockerfile: src/load-generator/Dockerfile
  - image: otel-demo/payment
    context: .
    docker:
      dockerfile: src/payment/Dockerfile
  - image: otel-demo/postgres
    context: .
    docker:
      dockerfile: src/postgres/Dockerfile
  - image: otel-demo/product-catalog
    context: .
    docker:
      dockerfile: src/product-catalog/Dockerfile
  - image: otel-demo/quote
    context: .
    docker:
      dockerfile: src/quote/Dockerfile
  - image: otel-demo/recommendation
    context: .
    docker:
      dockerfile: src/recommendation/Dockerfile
  - image: otel-demo/shipping
    context: .
    docker:
      dockerfile: src/shipping/Dockerfile
manifests:
  rawYaml:
    - kubernetes/*
deploy:
  kubectl:
    defaultNamespace: otel-demo
portForward:
  - resourceType: service
    resourceName: frontend-proxy
    namespace: otel-demo
    port: 8080
    localPort: 8080