apiVersion: skaffold/v3
kind: Config
metadata:
  name: opentelemetry-demo
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false # Defaults to false for local clusters, true for remote
    tryImportMissing: true # Don't rebuild if the image already exists locally
    useBuildkit: true
  artifacts:
  - image: accounting
    context: .
    docker:
      dockerfile: src/accounting/Dockerfile
  - image: ad
    context: .
    docker:
      dockerfile: src/ad/Dockerfile
  - image: cart
    context: .
    docker:
      dockerfile: src/cart/src/Dockerfile
  - image: checkout
    context: .
    docker:
      dockerfile: src/checkout/Dockerfile
  - image: currency
    context: .
    docker:
      dockerfile: src/currency/Dockerfile
  - image: email
    context: .
    docker:
      dockerfile: src/email/Dockerfile
  - image: flagd-ui
    context: .
    docker:
      dockerfile: src/flagd-ui/Dockerfile
  - image: fraud-detection
    context: .
    docker:
      dockerfile: src/fraud-detection/Dockerfile
  - image: frontend
    context: .
    docker:
      dockerfile: src/frontend/Dockerfile
  - image: frontend-proxy
    context: .
    docker:
      dockerfile: src/frontend-proxy/Dockerfile
  - image: image-provider
    context: .
    docker:
      dockerfile: src/image-provider/Dockerfile
  - image: kafka
    context: .
    docker:
      dockerfile: src/kafka/Dockerfile
  - image: load-generator
    context: .
    docker:
      dockerfile: src/load-generator/Dockerfile
  - image: payment
    context: .
    docker:
      dockerfile: src/payment/Dockerfile
  - image: postgres
    context: .
    docker:
      dockerfile: src/postgres/Dockerfile
  - image: product-catalog
    context: .
    docker:
      dockerfile: src/product-catalog/Dockerfile
  - image: quote
    context: .
    docker:
      dockerfile: src/quote/Dockerfile
  - image: recommendation
    context: .
    docker:
      dockerfile: src/recommendation/Dockerfile
  - image: shipping
    context: .
    docker:
      dockerfile: src/shipping/Dockerfile
manifests:
  rawYaml:
    - kubernetes/*