# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0



source "https://rubygems.org"

gem 'logger', '~> 1.7'
gem "net-smtp", "~> 0.5.1"
gem "pony",     "~> 1.13"
gem "puma",     "~> 8.0"
gem "sinatra",  "~> 4.2"
gem "rackup",   "~> 2.3"

gem "google-protobuf", "~> 4.34.1"

gem "ostruct"

gem "openfeature-sdk", "~> 0.6"
gem "openfeature-flagd-provider", "~> 0.1"
