"""
Test 3: Verify the de-otelified Kubernetes manifest is valid and complete.

Uses 'kubectl apply --dry-run=client' to validate the manifest without
connecting to a cluster. Also asserts that all expected application-level
Deployments are present (the pipeline must not delete application services
while removing OTel infrastructure).

Run individually:
    pytest tests/test_kubernetes_dry_run.py -v
"""

import shutil
import subprocess

import pytest
import yaml

KUBERNETES_MANIFEST = "kubernetes/opentelemetry-demo.yaml"

# All application service Deployments that must survive de-otelification.
# OTel infrastructure (jaeger, grafana, prometheus, opensearch, otel-collector)
# must be REMOVED; everything below must be KEPT.
# App-service Deployments that must survive de-otelification — calibrated to this
# fork's base manifest. (flagd-ui is folded into the flagd pod here, not standalone.)
EXPECTED_DEPLOYMENTS = {
    "accounting",
    "ad",
    "cart",
    "checkout",
    "currency",
    "email",
    "flagd",
    "fraud-detection",
    "frontend",
    "frontend-proxy",
    "image-provider",
    "kafka",
    "load-generator",
    "payment",
    "postgresql",
    "product-catalog",
    "quote",
    "recommendation",
    "shipping",
    "valkey-cart",
}


@pytest.mark.slow
@pytest.mark.k8s
def test_kubernetes_manifest_exists(project_root):
    """Assert the Kubernetes manifest file was generated by the pipeline."""
    manifest = project_root / KUBERNETES_MANIFEST
    assert manifest.exists(), (
        f"Kubernetes manifest not found: {manifest}\n"
        f"Expected the pipeline to generate: {KUBERNETES_MANIFEST}"
    )


@pytest.mark.slow
@pytest.mark.k8s
def test_kubernetes_dry_run(project_root):
    """
    Validates the de-otelified Kubernetes manifest with kubectl --dry-run=client.

    'client' mode validates schema locally without contacting an API server,
    so no cluster connection or kubeconfig is required — only kubectl.

    Skipped if kubectl is not installed in PATH.
    """
    kubectl = shutil.which("kubectl")
    if kubectl is None:
        pytest.skip("kubectl not found in PATH — install kubectl to run this test")

    manifest = project_root / KUBERNETES_MANIFEST
    if not manifest.exists():
        pytest.skip(f"Kubernetes manifest not found: {manifest}")

    result = subprocess.run(
        [kubectl, "apply", "--dry-run=client", "-f", str(manifest)],
        capture_output=True,
        text=True,
        cwd=project_root,
    )

    # Print kubectl warnings (deprecated fields) as informational, not failures
    if result.stderr:
        for line in result.stderr.splitlines():
            if line.startswith("Warning:"):
                print(f"[kubectl warning] {line}")

    if result.returncode != 0:
        pytest.fail(
            f"kubectl apply --dry-run=client failed (exit code {result.returncode}).\n"
            f"\nstdout:\n{result.stdout}\n"
            f"\nstderr:\n{result.stderr}"
        )


@pytest.mark.fast
@pytest.mark.k8s
def test_all_expected_deployments_present(project_root):
    """
    All application service Deployments must survive de-otelification.

    The pipeline must ONLY remove OTel infrastructure (jaeger, grafana,
    prometheus, opensearch, otel-collector) and OTel env vars. It must NOT
    delete application-level Deployments. This test catches the failure mode
    where the LLM transformation is too aggressive and removes real services.
    """
    manifest = project_root / KUBERNETES_MANIFEST
    if not manifest.exists():
        pytest.skip(f"Kubernetes manifest not found: {manifest}")

    docs = list(yaml.safe_load_all(manifest.read_text(encoding="utf-8")))
    found_deployments = {
        doc["metadata"]["name"]
        for doc in docs
        if doc
        and doc.get("kind") == "Deployment"
        and "metadata" in doc
        and "name" in doc["metadata"]
    }

    otel_infra = {"jaeger", "grafana", "prometheus", "opensearch", "otel-collector"}
    otel_present = found_deployments & otel_infra
    if otel_present:
        pytest.fail(
            f"OTel infrastructure Deployments must be removed but are still present: "
            f"{sorted(otel_present)}"
        )

    missing = EXPECTED_DEPLOYMENTS - found_deployments
    if missing:
        pytest.fail(
            f"Application Deployments missing from kubernetes manifest: {sorted(missing)}\n"
            f"Found Deployments: {sorted(found_deployments)}\n"
            f"The pipeline is incorrectly deleting application service Deployments."
        )
