"""
Canonical definition of "what counts as OpenTelemetry" for this repository.

This module is the single source of truth shared by:
  - tests/test_otel_absence.py  — the verification gate that fails if any OTel
    reference survives in the tree.
  - sync/residual_scan.py       — the post-merge scan that catches OTel that
    upstream re-introduced through a clean merge (no conflict).

Keeping both consumers on the same rule set means the sync pipeline cleans
exactly what the test suite checks for — no drift between "what we remove" and
"what we assert is gone".

Two kinds of checks:
  1. CONTENT rules (``RULES``): per-file-type regexes scanned line-by-line.
  2. FORBIDDEN-PATH globs (``FORBIDDEN_PATH_GLOBS``): whole directories that must
     not exist at all (the observability infra dirs we deleted). A clean upstream
     ADD into a deleted directory does not produce a merge conflict, so content
     scanning alone would miss it — hence a dedicated existence check.

Nothing here depends on pytest, so the sync pipeline can import it freely.
"""

from __future__ import annotations

import re
from pathlib import Path

# ─── Directories and extensions to never scan ─────────────────────────────────

EXCLUDE_DIRS = {
    "sync",         # pipeline code — legitimately contains OTel pattern strings
    ".github",      # CI config
    ".git",         # git internals
    "tests",        # the test suite itself
    "node_modules", # npm dependencies — Next.js bundles @opentelemetry/api internally
}

EXCLUDE_EXTENSIONS = {
    ".md", ".txt", ".rst",                     # documentation
    ".lock", ".sum",                            # lockfiles (auto-generated, regenerated by the pipeline)
    ".png", ".jpg", ".jpeg", ".svg", ".ico",   # images
    ".woff", ".woff2", ".ttf", ".eot",         # fonts
    ".pdf", ".zip", ".gz", ".tar",             # archives
}

# ─── Content rule definitions ─────────────────────────────────────────────────
# Each entry: (rule_id, glob_pattern, regex_patterns, description)
#
# glob_pattern is matched with root.rglob() after exclusions.
# regex_patterns are searched line-by-line (re.search, case-sensitive).
# Patterns in braces {a,b,c} are expanded manually (pathlib doesn't support them).

RULES = [
    # ── Python ────────────────────────────────────────────────────────────────
    (
        "py_imports",
        "**/*.py",
        [r"^from opentelemetry", r"^import opentelemetry"],
        "Python source: OTel import statements",
    ),
    (
        "py_deps",
        "**/requirements*.txt",
        [r"\bopentelemetry"],
        "requirements*.txt: OTel package reference",
    ),
    (
        "pyproject_deps",
        "**/pyproject.toml",
        [r"\bopentelemetry"],
        "pyproject.toml: OTel package reference",
    ),
    # ── JavaScript / TypeScript ───────────────────────────────────────────────
    (
        "js_imports",
        "**/*.{js,ts,jsx,tsx,mjs,cjs}",
        [
            r"""from\s+['"]@opentelemetry/""",
            r"""from\s+['"]opentelemetry""",
            r"""require\s*\(\s*['"]@?opentelemetry""",
        ],
        "JS/TS source: OTel import/require statements",
    ),
    (
        "js_package",
        "**/package.json",
        [r'"@opentelemetry/'],
        "package.json: @opentelemetry dependency",
    ),
    # ── Go ────────────────────────────────────────────────────────────────────
    (
        "go_source",
        "**/*.go",
        [r'"go\.opentelemetry\.io/'],
        "Go source: OTel import path",
    ),
    # go.mod: only flag DIRECT (non-indirect) OTel dependencies.
    # Indirect transitive deps (e.g. via connectrpc.com/otelconnect) are
    # acceptable since the service code itself does not import OTel.
    (
        "go_mod",
        "**/go.mod",
        [r"go\.opentelemetry\.io(?!.*//\s*indirect)"],
        "go.mod: direct OTel module dependency (indirect entries are acceptable)",
    ),
    # ── Rust ──────────────────────────────────────────────────────────────────
    (
        "rust_source",
        "**/*.rs",
        [r"\bopentelemetry\b"],
        "Rust source: OTel crate usage",
    ),
    (
        "cargo_toml",
        "**/Cargo.toml",
        [r"\bopentelemetry\b"],
        "Cargo.toml: OTel crate dependency",
    ),
    # ── C# / .NET ─────────────────────────────────────────────────────────────
    (
        "csharp_source",
        "**/*.cs",
        [r"using OpenTelemetry"],
        "C# source: using OpenTelemetry namespace",
    ),
    # OTel instrumentation in .NET is also expressed via System.Diagnostics
    # ActivitySource/Activity — which carry no `using OpenTelemetry` and so evade
    # the rule above. `new ActivitySource(...)` and `.StartActivity(...)` are the
    # tracing primitives; flagging them (not the broad `using System.Diagnostics`,
    # which is also used for Stopwatch/Process) keeps false positives away.
    (
        "csharp_activitysource",
        "**/*.cs",
        [r"\bnew ActivitySource\s*\(", r"\.StartActivity\s*\("],
        "C# source: ActivitySource/Activity tracing primitive",
    ),
    (
        "csproj",
        "**/*.csproj",
        [r"OpenTelemetry"],
        ".csproj: OTel package reference",
    ),
    # ── Java / Kotlin ─────────────────────────────────────────────────────────
    (
        "java_source",
        "**/*.java",
        [r"import io\.opentelemetry"],
        "Java source: OTel import",
    ),
    (
        "kotlin_source",
        "**/*.kt",
        [r"import io\.opentelemetry"],
        "Kotlin source: OTel import (fraud-detection service)",
    ),
    (
        "gradle",
        "**/*.{gradle,gradle.kts}",
        # Genuine OTel artifacts only — NOT the demo's own identity (group/namespace/
        # project name under io.opentelemetry) or copyright headers, which this fork keeps.
        [r"(?i)io\.opentelemetry:opentelemetry-"
         r"|io\.opentelemetry\.instrumentation"
         r"|opentelemetry-(?:api|sdk|instrumentation|javaagent|exporter|bom|semconv|extension|context|annotations)"],
        "Gradle build file: OTel dependency",
    ),
    (
        "maven_pom",
        "**/pom.xml",
        [r"opentelemetry"],
        "pom.xml: OTel dependency",
    ),
    # ── Elixir ────────────────────────────────────────────────────────────────
    (
        "mix_exs",
        "**/mix.exs",
        [r"opentelemetry"],
        "mix.exs: OTel hex dependency (flagd-ui service)",
    ),
    # ── Dockerfiles ───────────────────────────────────────────────────────────
    (
        "dockerfile_otel_arg",
        "**/Dockerfile*",
        [r"ARG\s+OTEL_", r"ARG\s+OPENTELEMETRY_"],
        "Dockerfile: OTel build ARG",
    ),
    (
        "dockerfile_javaagent",
        "**/Dockerfile*",
        [r"opentelemetry-javaagent\.jar"],
        "Dockerfile: Java OTel agent jar",
    ),
    (
        "dockerfile_instrument",
        "**/Dockerfile*",
        [r"opentelemetry-instrument", r"--require=\./opentelemetry\.js"],
        "Dockerfile: OTel instrumentation entrypoint wrapper",
    ),
    # ── docker-compose.yml ────────────────────────────────────────────────────
    (
        "compose_otel_env",
        "docker-compose.yml",
        [r"\bOTEL_"],
        "docker-compose.yml: OTEL_ environment variable",
    ),
    (
        "compose_otel_services",
        "docker-compose.yml",
        [
            # Match a top-level service key definition for OTel infra services
            r"^\s+(jaeger|grafana|prometheus|otel-collector|opensearch):\s*$",
        ],
        "docker-compose.yml: OTel infrastructure service still present",
    ),
    # ── Kubernetes manifests ──────────────────────────────────────────────────
    (
        "k8s_otel_env",
        "kubernetes/**/*.yaml",
        [r"\bOTEL_"],
        "kubernetes/: OTEL_ environment variable",
    ),
    (
        "k8s_otel_collector",
        "kubernetes/**/*.yaml",
        [r"\botel-collector\b"],
        "kubernetes/: otel-collector service reference",
    ),
    # NOTE: this fork keeps `opentelemetry.io/*` k8s labels (the demo's identity
    # labels, used as Service/Deployment selectors) — they are not instrumentation,
    # so there is deliberately no rule flagging them.
]

# ─── Forbidden observability directories ──────────────────────────────────────
# These directories are pure observability infrastructure and were deleted during
# de-otelification. They must never reappear. A clean upstream ADD into a deleted
# directory merges without conflict, so this existence check guards a gap that the
# content rules above cannot see.

FORBIDDEN_PATH_GLOBS = [
    "src/grafana/**/*",
    "src/jaeger/**/*",
    "src/otel-collector/**/*",
    "src/prometheus/**/*",
    "src/opensearch/**/*",
]


# ─── Helpers ──────────────────────────────────────────────────────────────────


def is_excluded(path: Path, root: Path) -> bool:
    """Return True if this file should be skipped by the OTel scan."""
    try:
        relative = path.relative_to(root)
    except ValueError:
        return True
    if any(part in EXCLUDE_DIRS for part in relative.parts):
        return True
    if path.suffix.lower() in EXCLUDE_EXTENSIONS:
        return True
    return False


def expand_brace_pattern(pattern: str) -> list[str]:
    """
    Expand patterns like **/*.{js,ts,jsx} into multiple patterns.
    pathlib.rglob does not support brace expansion.
    """
    if "{" not in pattern or "}" not in pattern:
        return [pattern]
    prefix, rest = pattern.split("{", 1)
    extensions_str, suffix = rest.split("}", 1)
    return [prefix + ext.strip() + suffix for ext in extensions_str.split(",")]


def glob_files(pattern: str, root: Path) -> list[Path]:
    """Resolve a glob pattern against ``root``, filtering excluded paths."""
    expanded = expand_brace_pattern(pattern)
    files: list[Path] = []
    for p in expanded:
        files.extend(f for f in root.rglob(p) if not is_excluded(f, root))
    # Deduplicate (a file could match multiple expanded patterns)
    seen: set[Path] = set()
    result: list[Path] = []
    for f in files:
        if f not in seen:
            seen.add(f)
            result.append(f)
    return result


def scan_file(path: Path, patterns: list[str]) -> list[tuple[int, str]]:
    """Return list of (line_number, line_content) for lines matching any pattern."""
    compiled = [re.compile(p) for p in patterns]
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except (OSError, PermissionError):
        return []
    matches = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if any(rx.search(line) for rx in compiled):
            matches.append((lineno, line.rstrip()))
    return matches


def scan_rule(
    rule_id: str, glob_pattern: str, patterns: list[str], root: Path
) -> dict[Path, list[tuple[int, str]]]:
    """Scan all files matching one rule; return {file: [(lineno, line), ...]}."""
    violations: dict[Path, list[tuple[int, str]]] = {}
    for f in glob_files(glob_pattern, root):
        hits = scan_file(f, patterns)
        if hits:
            violations[f] = hits
    return violations


def _glob_to_regex(pat: str) -> str:
    """Translate a glob to a regex, matching pathlib's rglob/git semantics:
    `**` spans zero or more path segments, `*` stays within a segment."""
    out: list[str] = []
    i = 0
    while i < len(pat):
        if pat[i : i + 3] == "**/":
            out.append("(?:.*/)?")   # zero or more leading segments
            i += 3
            continue
        if pat[i : i + 2] == "**":
            out.append(".*")
            i += 2
            continue
        c = pat[i]
        if c == "*":
            out.append("[^/]*")
        elif c == "?":
            out.append("[^/]")
        else:
            out.append(re.escape(c))
        i += 1
    return "".join(out)


def _path_matches(glob_pattern: str, rel_path: str) -> bool:
    """True if rel_path matches the rule's glob (consistent with glob_files)."""
    return any(
        re.fullmatch(_glob_to_regex(pat), rel_path) is not None
        for pat in expand_brace_pattern(glob_pattern)
    )


def scan_text(rel_path: str, text: str) -> list[tuple[str, int, str]]:
    """
    Scan an in-memory file's text against every rule whose glob matches its path.

    Returns [(rule_id, line_number, line), ...]. Used to validate a candidate
    resolution before it touches disk — no filesystem access required.
    """
    violations: list[tuple[str, int, str]] = []
    lines = text.splitlines()
    for rule_id, glob_pattern, patterns, _desc in RULES:
        if not _path_matches(glob_pattern, rel_path):
            continue
        compiled = [re.compile(p) for p in patterns]
        for i, line in enumerate(lines, start=1):
            if any(rx.search(line) for rx in compiled):
                violations.append((rule_id, i, line.rstrip()))
    return violations


def find_forbidden_paths(root: Path) -> list[Path]:
    """Return any files that exist under a forbidden observability directory."""
    found: list[Path] = []
    for pattern in FORBIDDEN_PATH_GLOBS:
        found.extend(f for f in root.glob(pattern) if f.is_file())
    return sorted(set(found))


def scan_tree(root: Path) -> dict[str, dict[Path, list[tuple[int, str]]]]:
    """
    Run every content rule plus the forbidden-path check against ``root``.

    Returns {rule_id: {file: [(lineno, line), ...]}}. Only rules with at least one
    violation are included. The forbidden-path check is reported under the synthetic
    rule id "forbidden_telemetry_path" with a sentinel line of (0, "<file exists>").
    """
    result: dict[str, dict[Path, list[tuple[int, str]]]] = {}
    for rule_id, glob_pattern, patterns, _desc in RULES:
        violations = scan_rule(rule_id, glob_pattern, patterns, root)
        if violations:
            result[rule_id] = violations
    forbidden = find_forbidden_paths(root)
    if forbidden:
        result["forbidden_telemetry_path"] = {f: [(0, "<file exists>")] for f in forbidden}
    return result
